### ISSUE TITLE
Cant jump forward under certain conditions

### ISSUE THREAD

**Issue by seriousdev-gh** [qhdwight/bevy_fps_controller#10]
I can't say it's a bug. Maybe this is intentional behavior.

Steps to reproduce:
- press forward
- press jump
- wait some time to gain speed
- rotate camera by 90 degrees
- character will jump to right or left but never forward in the direction of camera view

**Comment by qhdwight** [comment]
Not sure if I understand how to reproduce. To move you will need to strafe like in the Source Engine. So release W and move A and D in the direction of your camera.

**Comment by seriousdev-gh** [comment]
Just tested in half life 2, behaviour is same, so its not a bug. But if you hold space button in half life 2 you jump once, in this fps controller you jumping continuously, this makes the described behavior more visible.

**Comment by qhdwight** [comment]
The continuous jumping is intentional, but I should probably make it an option. Would be worth opening another issue for that.
