### ISSUE TITLE
Add crouching

### ISSUE THREAD

**Issue by Aronry** [qhdwight/bevy_fps_controller#12]
I made a fairly decent crouch mechanic: 
https://github.com/Aronry/bevy_fps_controller/pull/1

If it checks out, let me know if I should open a PR.

**Comment by qhdwight** [comment]
Hey, thank you for the code, crouching has definitely been something I've wanted to add for a while.

It would be great if you opened the PR to this repository!

Sorry for the late response I am wrapping up from the holidays and started my term.

**Comment by qhdwight** [comment]
Added with #14 thank you for bringing up this feature and providing a good start
