### ISSUE TITLE
Is Surfing Bug Intentional?

### ISSUE THREAD

**Issue by Zrocket** [qhdwight/bevy_fps_controller#29]
I was playing with the example level and noticed that you can almost surf on the incline. Since this is inspired by the source engine, I wanted to know if surfing is intentional? If so, there's still a bug that propels you upward instead of forward when strafing into the incline. If not, we'll need to patch it out entirely.

For those who don't know, surfing is a source engine physics engine bug that's been adopted by the community as a feature.

**Comment by Zrocket** [comment]
Here's a video showcasing surfing in the original source engine:

[https://www.youtube.com/watch?v=7ROMtcdu8kY](url)

**Comment by Zrocket** [comment]
Vertical climbing seems to stop around gravity value 42.3. You can start climbing the incline, but eventually you lose momentum and stop.

**Comment by Zrocket** [comment]
I created a pull request that solves walking up slopes, but at the cost of removing surfing.

**Comment by Zrocket** [comment]
We can probably add a flag to the player controller structure to enable surfing as an optional feature.

**Comment by qhdwight** [comment]
I was intending surfing to be possible, but like you pointed out I could not figure out the random force that propels you up the slope.

Under a certain configurable threshold I would like the intended behavior to be walking.

**Comment by Zrocket** [comment]
It took me a minute, but the upward force is a result of the player's x and z velocity. In the pull request you can see I disabled them if there's not enough traction, but not if the player is in the air (eg jumping). 

This is because as the player walks into the slope the collider pushes it upward, even when gravity should be pulling you downward.

**Comment by Zrocket** [comment]
I'll have to play around with the velocity since more, but theoretically we can probably find a value that's in relative equilibrium with gravity. That way you can still surf, and even use gained momentum to go up a bit, but prevents you from just walking up.

**Comment by Zrocket** [comment]
I think I've developed the start of a surf system. First, it checks if surf_allowed is true, and multiplies add.x and add.z by 0.2. Otherwise, it just sets them to 0.0. It's still hard to test without a proper surf map, though.
