### ISSUE TITLE
Character velocity depends on camera pitch

### ISSUE THREAD

**Issue by seriousdev-gh** [qhdwight/bevy_fps_controller#9]
If you look up or down and press W the character will stand still. And gradually pick up speed as the camera angle approaches the horizon.

**Comment by qhdwight** [comment]
Ah that is true. I have to check in Source Engine if this is the same behavior lol

**Comment by qhdwight** [comment]
Ok yeah just tried in CSGO, I'll try to fix

**Comment by qhdwight** [comment]
Fixing with: #11
